### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by FIFARenderZ** [FIFARenderZ/wwi-webshop#1]
Check products.php op SQL injection

**Comment by francofico** [comment]
@FIFARenderZ Hey man, I found your repo while searching for a final project of a university subject. We need to find free software projects which have some kind of security vulnerability, fix it and patch it; so I was wondering if we could use your code and fix this issue. We would send to you the patched code afterwards.
If you want to know more, please answer here tagging me and I'll contact you.

**Comment by FIFARenderZ** [comment]
> @FIFARenderZ Hey man, I found your repo while searching for a final project of a university subject. We need to find free software projects which have some kind of security vulnerability, fix it and patch it; so I was wondering if we could use your code and fix this issue. We would send to you the patched code afterwards.
> If you want to know more, please answer here tagging me and I'll contact you.

Yeah it's an open repo so feel free to use it. Only the bootstrap theme (Material Kit) needs a license, so be careful with that. This was made for a school project as well, so it matches the theme 😆
